In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
df = pd.read_csv('Zip_Zri_AllHomesPlusMultifamily.csv', dtype={'RegionName': str})

In [2]:
targets = df
targets

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
0,61639,10025,New York,NY,New York-Newark-Jersey City,New York County,1,3031.0,3058.0,3031.0,3015.0,2976.0,2914.0,2860.0,2811.0,2792.0,2799.0,2820.0,2852.0,2885.0,2905.0,2883.0,2879.0,2905.0,2916.0,2908.0,2915.0,2920.0,2920.0,2938.0,2999.0,3029.0,3022.0,3049.0,3083.0,3086.0,3072.0,3081.0,3095.0,3147.0,3190.0,3188.0,3149.0,3149.0,3174.0,3175.0,3230.0,3267.0,3285.0,3234.0,3296.0,3357.0,3366.0,NaN,3186.0,3204.0,NaN,NaN,NaN,3682.0,3767.0,3767.0,3811.0,3793.0,3894.0,3919.0,NaN,NaN,NaN,NaN,4166.0,4164.0,4133.0,4015.0,3943.0,3945.0,4051.0,NaN,NaN,NaN,NaN,4916.0,NaN,5009.0,NaN,NaN,NaN,NaN,3988.0,NaN,NaN,3661.0,NaN,NaN,NaN,NaN,3512.0,3552.0,NaN,3768.0,3731.0,3634.0,NaN,NaN,3300.0,3227.0,NaN,NaN,NaN,NaN,3785.0,3788.0,3786.0,3784.0,3766.0,3779.0,3843.0,3873.0,3835.0,NaN
1,84654,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,1790.0,1787.0,1784.0,1774.0,1755.0,1742.0,1735.0,1741.0,1742.0,1757.0,1790.0,1817.0,1839.0,1841.0,1844.0,1844.0,1820.0,1818.0,1829.0,1843.0,1860.0,1878.0,1898.0,1889.0,1890.0,1894.0,1897.0,1886.0,1884.0,1887.0,1907.0,1918.0,1925.0,1948.0,1996.0,2017.0,2011.0,2002.0,1989.0,1984.0,1979.0,1976.0,1969.0,1989.0,1996.0,2001.0,2006.0,2009.0,2032.0,2045.0,2038.0,2028.0,2016.0,2028.0,2033.0,2027.0,2041.0,2071.0,2100.0,2136.0,2139.0,2119.0,2093.0,2079.0,2061.0,2058.0,2079.0,2100.0,2115.0,2150.0,2184.0,2201.0,2212.0,2207.0,2182.0,2136.0,2108.0,2104.0,2117.0,2118.0,2125.0,2146.0,2168.0,2183.0,2165.0,2128.0,2097.0,2070.0,2057.0,2052.0,2054.0,2061.0,2074.0,2106.0,2134.0,2146.0,2155.0,2149.0,2116.0,2076.0,2025.0,2014.0,2017.0,2039.0,2070.0,2105.0,2140.0,2168.0,2185.0,2125.0,NaN,2053.0,1996.0
2,61637,10023,New York,NY,New York-Newark-Jersey City,New York County,3,3269.0,3304.0,3320.0,3322.0,3283.0,3225.0,3133.0,3086.0,3017.0,3005.0,3010.0,3016.0,3028.0,3069.0,3020.0,2999.0,2988.0,3023.0,3037.0,3055.0,3069.0,3058.0,3065.0,3104.0,3117.0,3118.0,3124.0,3128.0,3098.0,3078.0,3119.0,3150.0,3183.0,3227.0,3233.0,3199.0,3217.0,3255.0,3274.0,3346.0,3357.0,3363.0,3287.0,3312.0,3385.0,3385.0,NaN,3231.0,3258.0,NaN,NaN,NaN,NaN,4011.0,3985.0,4026.0,4012.0,NaN,NaN,NaN,NaN,NaN,NaN,4734.0,4800.0,4690.0,4693.0,NaN,4418.0,4534.0,NaN,4753.0,4687.0,4788.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4176.0,NaN,3997.0,3924.0,NaN,NaN,NaN,NaN,3802.0,3809.0,3900.0,3999.0,4043.0,3957.0,NaN,NaN,3611.0,3560.0,NaN,NaN,NaN,3928.0,3874.0,3898.0,3917.0,3929.0,3931.0,3963.0,NaN,4123.0,4079.0,NaN
3,91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,1547.0,1549.0,1560.0,1560.0,1542.0,1547.0,1559.0,1578.0,1591.0,1597.0,1604.0,1609.0,1607.0,1598.0,1591.0,1591.0,1606.0,1614.0,1617.0,1612.0,1611.0,1617.0,1630.0,1640.0,1649.0,1655.0,1658.0,1658.0,1661.0,1675.0,1698.0,1727.0,1753.0,1771.0,1789.0,1808.0,1852.0,1882.0,1906.0,1920.0,1930.0,1936.0,1931.0,1925.0,1929.0,1935.0,1953.0,1967.0,1984.0,1994.0,1999.0,1999.0,1945.0,1917.0,1906.0,1903.0,1908.0,1919.0,1933.0,1944.0,1931.0,1924.0,1918.0,1915.0,1881.0,1859.0,1839.0,1828.0,1827.0,1826.0,1830.0,1826.0,1801.0,1782.0,1772.0,1767.0,1765.0,1763.0,1762.0,1760.0,1752.0,1753.0,1757.0,1763.0,1777.0,1791.0,1799.0,1799.0,1796.0,1791.0,1791.0,1789.0,1787.0,1790.0,1795.0,1790.0,1787.0,1782.0,1779.0,1781.0,1774.0,1773.0,1769.0,1765.0,1755.0,1751.0,1752.0,1754.0,1759.0,1764.0,1769.0,1776.0,1778.0
4,84616,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,1922.0,1925.0,1921.0,1908.0,1870.0,1841.0,1825.0,1823.0,1829.0,1850.0,1894.0,1937.0,1966.0,1977.0,1982.0,1977.0,1950.0,1945.0,1956.0,1980.0,1989.0,2012.0,2021.0,2021.0,2035.0,2076.0,2093.0,2098.0,2114.0,2123.0,2119.0,2113.0,2096.0,2108.0,2153.0,2189.0,2192.0,2190.0,2186.0,2193.0,2169.0,2156.0,2145.0,2167.0,2182.0,2191.0,2204.0,2222.0,2247.0,2253.0,2254.0,2241.0,2227.0,2232.0,2233.0,2219.0,2230.0,2262.0,2291.0,2331.0,2338.0,2318.0,2293.0,2278.0,2255.0,2265.0,2291.0,2312.0,2330.0,2356.0,2386.0,2405.0,2421.0,2413.0,2382.0,2342.0,2313.0,2307.0,2319.0,2325.0,2338.0,2364.0,2389.0,2401.0,2391.0,2364.0,2327.0,2290.0,2277.0,2282.0,2290.0,2306.0,2312.0,2333.0,2358.0,2353.0,2360.0,2344.0,2296.0,2260.0,2204.0,2199.0,2213.0,2245.0,2289.0,2332.0,2372.0,2398.0,2412.0,2348.0,2356.0,2311.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13176,68966,26291,Snowshoe,WV,NaN,Pocahontas County,13177,946.0,NaN,NaN,NaN,NaN,1004.0,987.0,970.0,959.0,941.0,944.0,951.0,962.0,953.0,941.0,918.0,890.0,914.0,926.0,934.0,927.0,921.0,926.0,NaN,984.0,995.0,1006.0,1022.0,1021.0,994.0,968.0,954.0,959.0,973.0,992.0,1003.0,996.0,977.0,NaN,935.0,928.0,925.0,918.0,916.0,920.0,928.0,942.0,948.0,NaN,1007.0,1007.0,1004.0,1002.0,1002.0,1006.0,1003.0,1016.0,1036.0,1047.0,1057.0,1068.0,1083.0,1066.0,1050.0,1042.0,1034.0,1028.0,1026.0,1022.0,1015.0,1022.0,1019.0,1029.0,1024.0,1010.0,988.0,993.0,984.0,968.0,965.0,964.0,964.0,955.0,943.0,933.0,917.0,906.0,904.0,901.0,897.0,898.0,897.0,901.0,902.0,913.0,933.0,944.0,944.0,938.0,953.0,961.0,965.0,966.0,965.0,959.0,956.0,958.0,956.0,951.0,932.0,928.0,930.0,923.0
13177,62697,12720,Bethel,NY,NaN,Sullivan County,13178,1372.0,1390.0,1417.0,1417.0,1419.0,NaN,NaN,NaN,NaN,1150.0,1150.0,1165.0,1179.0,1189.0,1184.0,1165.0,1149.0,1134.0,1128.0,1113.0,1100.0,1104.0,NaN,1171.0,1188.0,1200.0,1197.0,1190.0,1194.0,1192.0,1199.0,1198.0,1200.0,1206.0,1214.0,1214.0,1214.0,1201.0,1187.0,1183.0,1192.0,1196.0,1214.0,1218.0,1213.0,1210.0,1214.0,1213.0,1201.0,1210.0,1219.0,1217.0,1196.0,NaN,1113.0,1092.0,1091.0,1108.0,1125.0,1131.0,1150.0,1159.0,1161.0,1152.0,1158.0,1176.0,1187.0,1201.0,1212.0,1208.0,1198.0,1202.0,1206.0,1208.0,1207.0,1195.0,1162.0,1154.0,1147.0,1145.0,1155.0,1172.0,1186.0,1206.0,1212.0,1215.0,1212.0,1211.0,1209.0,1211.0,1232.0,1241.0,1256.0,1275.0,1276.0,1276.0,1276.0,1288.0,1290.0,1305.0,1291.0,1281.0,1272.0,1279.0,1284.0,1288.0,1295.0,1294.0,1305.0,NaN,1348.0,1310.0,1272.0
13178,68924,26209,Snowshoe,WV,NaN,Pocahontas County,13179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,697.0,700.0,695.0,688.0,681.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,765.0,763.0,772.0,776.0,NaN,NaN,NaN,735.0,733.0,734.0,731.0,740.0,734.0,732.0,728.0,729.0,729.0,732.0,735.0,746.0,752.0,765.0,770.0,770.0,771.0,764.0,761.0,760.0,764.0,771.0,758.0,756.0,768.0,782.0,796.0,782.0,775.0,764.0,759.0,755.0,750.0,747.0,NaN,NaN,739.0,730.0,728.0,727.0,725.0,724.0,745.0,762.0,779.0,NaN,NaN,765.0
13179,75924,41101,Ashland,KY,Huntington-Ashland,Boyd County,13180,758.0,754.0,760.0,761.0,761.0,764.0,767.0,765.0,760.0,762.0,779.0,789.0,793.0,803.0,816.0,829.0,824.0,819.0,818.0,819.0,834.0,843.0,849.0,854.0,868.0,876.0,879.0,870.0,856.0,843.0,832.0,827.0,823.0,825.0,826.0,829.0,831.0,830.0,835.0,836.0,838.0,839.0,836.0,831.0,828.0,826.0,834.0,842.0,845.0,840.0,838.0,837.0,841.0,842.0,841.0,841.0,845.0,845.0,837.0,841.0,844.0,862.0,863.0,861.0,859.0,855.0,853.0,852.0,859.0,865.0,869.0,876.0,876.0,874.0,873.0,870.0,860.0,855.0,851.0,850.0,855.0,861.0,867.0,863.0,854.0,840.0,832.0,832.0,829.0,831.0,851.0,872.0,880.0,870.0,863.0,858.0,856.0,851.0,857.0,853.0,861.0,861.0,857.0,852.0,850.0,847.0,842.0,836.0,836.0,829.0,853.0,828.0,815.0
13180,95851,89155,Las Vegas,NV,Las Vegas-Henderson-Paradise,Clark County,13181,1087.0,1098.0,1104.0,1110.0,1113.0,1111.0,1108.0,1106.0,1102.0,1099.0,1089.0,1092.0,1085.0,1085.0,1086.0,1085.0,1090.0,1093.0,1093.0,1093.0,1093.0,1093.0,1094.0,1090.0,1082.0,1082.0,1078.0,1074.0,1073.0,1076.0,1079.0,1086.0,1093.0,1098.0,1102.0,1104.0,1108.0,1111.0,1140.0,1122.0,1135.0,1141.0,1141.0,1135.0,1121.0,1115.0,1124.0,1134.0,1149.0,1159.0,1169.0,1169.0,1174.0,1178.0,1176.0,1185.0,1195.0,1201.0,1207.0,1216.0,1221.0,1223.0,1226.0,1232.0,1236.0,1239.0,1240.0,1241.0,1247.0,1254.0,1259.0,1263.0,1268.0,1268.0,1270.0,1268.0,1263.0,1263.0,1259.0,1267.0,1272.0,1278.0,1284.0,1289.0,1300.0,1292.0,1284.0,1280.0,1280.0,1284.0,1286.0,1290.0,1297.0,1301.0,1303.0,1306.0,1306.0,1312.0,1314.0,1313.0,1309.0,1308.0,1307.0,1309.0,1316.0,1324.0,1332.0,1340.0,1369.0,1406.0,1430.0,1441.0,1429.0

In [4]:
targets2 = pd.read_csv('Zip_ZORI_AllHomesPlusMultifamily_Smoothed.csv')
targets2

,RegionID,RegionName,SizeRank,MsaName,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10
0,61639,10025,1,"New York, NY",2792.0,2720.0,2801.0,2823.0,2815.0,2822.0,2869.0,2892.0,2872.0,2903.0,2900.0,2941.0,2955.0,2938.0,2938.0,2941.0,2961.0,2982.0,2992.0,2993.0,3001.0,3008.0,2991.0,2992.0,3012.0,2997.0,3018.0,3021.0,3022.0,3043.0,2983.0,3022.0,3053.0,3018.0,2998.0,2985.0,2990.0,2973.0,2939.0,2984.0,3045.0,3048.0,3054.0,3060.0,3033.0,3000.0,2986.0,3020.0,2978.0,2976.0,2960.0,3011.0,3045.0,3052.0,3068.0,3061.0,3047.0,3043.0,3043.0,3061.0,3074.0,3059.0,3061.0,3074.0,3094.0,3128.0,3147.0,3171.0,3163.0,3099.0,3125.0,3109.0,3125.0,3149.0,3102.0,3108.0,3076.0,3012.0,2951.0,2846.0,2734.0,2695.0,2668.0,2638.0,2673.0,2650.0,2714.0,2772.0,2853.0,2914.0,2995.0,3064.0,3086.0,3137.0
1,84654,60657,2,"Chicago, IL",1242.0,1269.0,1270.0,1277.0,1292.0,1322.0,1323.0,1324.0,1312.0,1304.0,1299.0,1300.0,1299.0,1309.0,1303.0,1327.0,1350.0,1367.0,1374.0,1381.0,1356.0,1345.0,1339.0,1345.0,1336.0,1351.0,1370.0,1385.0,1400.0,1412.0,1418.0,1421.0,1409.0,1387.0,1373.0,1370.0,1383.0,1401.0,1418.0,1424.0,1431.0,1441.0,1446.0,1437.0,1425.0,1409.0,1401.0,1393.0,1403.0,1417.0,1429.0,1441.0,1453.0,1459.0,1458.0,1442.0,1433.0,1407.0,1391.0,1387.0,1414.0,1427.0,1444.0,1463.0,1473.0,1481.0,1489.0,1473.0,1472.0,1451.0,1442.0,1433.0,1467.0,1479.0,1486.0,1490.0,1484.0,1476.0,1469.0,1462.0,1428.0,1393.0,1393.0,1407.0,1420.0,1433.0,1436.0,1439.0,1454.0,1461.0,1465.0,1483.0,1481.0,1475.0
2,61637,10023,3,"New York, NY",3088.0,3109.0,3148.0,3139.0,3158.0,3218.0,3207.0,3212.0,3213.0,3192.0,3259.0,3216.0,3196.0,3217.0,3252.0,3223.0,3241.0,3267.0,3265.0,3288.0,3297.0,3303.0,3300.0,3279.0,3253.0,3288.0,3305.0,3315.0,3324.0,3320.0,3150.0,3221.0,3255.0,3285.0,3230.0,3228.0,3209.0,3260.0,3267.0,3322.0,3319.0,3338.0,3336.0,3315.0,3287.0,3284.0,3262.0,3228.0,3246.0,3262.0,3281.0,3307.0,3336.0,3333.0,3307.0,3330.0,3343.0,3328.0,3298.0,3272.0,3269.0,3280.0,3296.0,3344.0,3374.0,3407.0,3413.0,3407.0,3417.0,3342.0,3295.0,3327.0,3374.0,3397.0,3409.0,3390.0,3338.0,3291.0,3215.0,3078.0,3036.0,2961.0,2868.0,2839.0,2865.0,2909.0,2940.0,3017.0,3069.0,3163.0,3263.0,3344.0,3465.0,3558.0
3,91982,77494,4,"Houston, TX",1370.0,1431.0,1438.0,1445.0,1420.0,1409.0,1412.0,1406.0,1404.0,1385.0,1383.0,1376.0,1381.0,1374.0,1379.0,1387.0,1391.0,1398.0,1403.0,1414.0,1396.0,1384.0,1380.0,1364.0,1359.0,1355.0,1357.0,1354.0,1352.0,1358.0,1351.0,1349.0,1337.0,1327.0,1301.0,1298.0,1306.0,1317.0,1322.0,1337.0,1340.0,1345.0,1335.0,1324.0,1336.0,1346.0,1353.0,1358.0,1367.0,1368.0,1362.0,1367.0,1368.0,1371.0,1369.0,1364.0,1351.0,1357.0,1361.0,1365.0,1367.0,1368.0,1375.0,1378.0,1378.0,1385.0,1389.0,1399.0,1379.0,1387.0,1387.0,1397.0,1390.0,1398.0,1397.0,1403.0,1389.0,1390.0,1398.0,1401.0,1414.0,1403.0,1421.0,1421.0,1419.0,1418.0,1421.0,1445.0,1475.0,1539.0,1582.0,1604.0,1607.0,1624.0
4,84616,60614,5,"Chicago, IL",1542.0,1566.0,1576.0,1589.0,1608.0,1624.0,1643.0,1641.0,1624.0,1613.0,1617.0,1590.0,1590.0,1603.0,1590.0,1636.0,1665.0,1691.0,1703.0,1716.0,1700.0,1697.0,1667.0,1646.0,1676.0,1697.0,1705.0,1719.0,1751.0,1771.0,1772.0,1771.0,1761.0,1719.0,1700.0,1694.0,1692.0,1727.0,1745.0,1772.0,1785.0,1788.0,1787.0,1791.0,1783.0,1748.0,1735.0,1733.0,1743.0,1771.0,1798.0,1795.0,1811.0,1819.0,1817.0,1809.0,1788.0,1752.0,1741.0,1747.0,1779.0,1803.0,1817.0,1837.0,1856.0,1856.0,1856.0,1859.0,1853.0,1834.0,1811.0,1829.0,1822.0,1846.0,1866.0,1889.0,1882.0,1867.0,1857.0,1834.0,1790.0,1743.0,1681.0,1659.0,1694.0,1748.0,1786.0,1832.0,1855.0,1875.0,1878.0,1914.0,1888.0,1898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,95039,85701,8456,"Tucson, AZ",NaN,963.0,939.0,906.0,907.0,920.0,956.0,948.0,922.0,915.0,938.0,950.0,942.0,931.0,NaN,940.0,937.0,972.0,990.0,1029.0,970.0,987.0,991.0,976.0,1006.0,987.0,NaN,973.0,1022.0,1021.0,1047.0,1032.0,1063.0,1031.0,1039.0,NaN,1038.0,1064.0,1056.0,1060.0,1051.0,1075.0,1080.0,1100.0,1087.0,1076.0,1127.0,1089.0,1122.0,1118.0,1081.0,1101.0,1117.0,1142.0,1135.0,1099.0,1081.0,1129.0,1152.0,1128.0,1123.0,1199.0,1199.0,1189.0,1197.0,1164.0,1188.0,1222.0,1259.0,1276.0,1272.0,1252.0,1275.0,1254.0,1245.0,1231.0,1188.0,1193.0,1260.0,1250.0,1212.0,1270.0,1323.0,NaN,1308.0,1277.0,1245.0,1279.0,1302.0,1299.0,1416.0,1469.0,1485.0,1409.0
2138,84608,60606,8497,"Chicago, IL",2073.0,2065.0,2091.0,2107.0,2117.0,2168.0,2177.0,2110.0,2073.0,2055.0,2064.0,2033.0,2115.0,2106.0,2077.0,2202.0,2218.0,2196.0,2221.0,2079.0,2050.0,NaN,2181.0,NaN,2004.0,1945.0,2008.0,2126.0,2305.0,2243.0,2215.0,2249.0,2230.0,2269.0,2136.0,2011.0,1913.0,1983.0,2077.0,2196.0,2199.0,2208.0,2207.0,2227.0,2248.0,2117.0,2132.0,NaN,2214.0,2400.0,2297.0,2312.0,2329.0,2288.0,2269.0,2216.0,2274.0,2332.0,2261.0,2220.0,2192.0,2241.0,2227.0,2296.0,2394.0,2418.0,2414.0,2452.0,2360.0,2339.0,2276.0,2264.0,2272.0,2253.0,2307.0,2343.0,2334.0,2279.0,2257.0,2193.0,2125.0,2020.0,1986.0,1907.0,1895.0,1952.0,2023.0,2122.0,2208.0,2307.0,2340.0,2387.0,2278.0,2212.0
2139,61620,10006,8506,"New York, NY",2671.0,2699.0,2723.0,2746.0,2807.0,2835.0,2877.0,2868.0,2877.0,2854.0,2875.0,2841.0,2841.0,2919.0,2909.0,2885.0,2968.0,3022.0,3041.0,3042.0,3036.0,3016.0,2989.0,2904.0,2815.0,2857.0,2877.0,2887.0,2957.0,2980.0,2934.0,2964.0,3031.0,3001.0,2932.0,2866.0,2870.0,2877.0,2918.0,2886.0,2910.0,2920.0,2947.0,2973.0,2966.0,2934.0,2873.0,2819.0,2825.0,2869.0,2863.0,2863.0,2884.0,2969.0,2980.0,3006.0,3028.0,3038.0,2992.0,2993.0,2929.0,2920.0,3036.0,3021.0,3044.0,3067.0,3090.0,3101.0,3115.0,3119.0,3058.0,3021.0,3053.0,3052.0,3093.0,3048.0,2973.0,2957.0,2873.0,2743.0,2573.0,2465.0,2457.0,2461.0,2382.0,2462.0,2449.0,2539.0,2571.0,2691.0,2772.0,2930.0,3001.0,3078.0
2140,58623,2109,8792,"Boston, MA",NaN,2863.0,NaN,3105.0,3141.0,3152.0,3140.0,3170.0,3200.0,3266.0,3474.0,3179.0,3067.0,3064.0,3132.0,3172.0,3255.0,3319.0,3234.0,3261.0,3306.0,3287.0,3268.0,3007.0,3163.0,3320.0,3197.0,3201.0,3212.0,3248.0,3266.0,3427.0,3337.0,3366.0,3237.0,3059.0,3140.0,3145.0,3187.0,3272.0,3326.0,3379.0,3337.0,3239.0,3184.0,3363.0,3415.0,3143.0,3256.0,3326.0,3246.0,3282.0,3324.0,3375.0,3340.0,3331.0,3329.0,3303.0,3249.0,3169.0,3281.0,3372.0,3394.0,3442.0,3436.0,3483.0,3457.0,3526.0,3441.0,3361.0,3439.0,3431.0,3440.0,3532.0,3583.0,3462.0,3410.0,3415.0,3370.0,3200.0,3093.0,3108.0,3023.0,3012.0,3080.0,3038.0,2993.0,3215.0,3296.0,3364.0,3365.0,3443.0,3497.0,3419.0
2141,62321,11976,9253,"New York, NY",101087.0,NaN,NaN,NaN,NaN,96349.0,90065.0,80332.0,NaN,83331.0,87535.0,96013.0,93658.0,NaN,108654.0,113907.0,NaN,NaN,97750.0,97137.0,97424.0,92744.0,93318.0,86159.0,87795.0,NaN,NaN,110572.0,105397.0,103697.0,92773.0,NaN,NaN,NaN,NaN,98959.0,89516.0,NaN,105934.0,110005.0,100166.0,91283.0,NaN,NaN,85695.0,88000.0,82300.0,NaN,NaN,89453.0,NaN,NaN,76355.0,72560.0,NaN,82883.0,81702.0,79869.0,82871.0,83007.0,80669.0,77821.0,79244.0,79696.0,74904.0,73913.0,71731.0,65778.0,69587.0,NaN,NaN,NaN,72531.0,70084.0,63464.0,58579.0,61292.0,62889.0,61452.0,NaN,46571.0,NaN,NaN,NaN,63816.0,NaN,NaN,NaN,NaN,90291.0,NaN,NaN,NaN,63635.0

In [ ]:
# I was thinking about trying to integrate the ZORI from the Zillow website into the targets file
# But upon further inspection I see that the values are totally different by maybe 20% or so. I could 
# try to combine them and multiply by a common scaling factor, but honestly that's messy and difficult 
# And I don't think now is the time to try that.

In [5]:
cols_2010 = targets.filter(regex='2010')
cols_2011 = targets.filter(regex='2011')
cols_2012 = targets.filter(regex='2012')
cols_2013 = targets.filter(regex='2013')
cols_2014 = targets.filter(regex='2014')
cols_2015 = targets.filter(regex='2015')
cols_2016 = targets.filter(regex='2016')
cols_2017 = targets.filter(regex='2017')
cols_2018 = targets.filter(regex='2018')
cols_2019 = targets.filter(regex='2019')
cols_2020 = targets.filter(regex='2020')

In [7]:
cols_2010['average'] = cols_2010.mean(axis=1)
cols_2011['average'] = cols_2011.mean(axis=1)
cols_2012['average'] = cols_2012.mean(axis=1)
cols_2013['average'] = cols_2013.mean(axis=1)
cols_2014['average'] = cols_2014.mean(axis=1)
cols_2015['average'] = cols_2015.mean(axis=1)
cols_2016['average'] = cols_2016.mean(axis=1)
cols_2017['average'] = cols_2017.mean(axis=1)
cols_2018['average'] = cols_2018.mean(axis=1)
cols_2019['average'] = cols_2019.mean(axis=1)
cols_2020['average'] = cols_2020.mean(axis=1)

/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2010['average'] = cols_2010.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2011['average'] = cols_2011.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2012['average'] = cols_2012.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2013['average'] = cols_2013.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2014['average'] = cols_2014.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2015['average'] = cols_2015.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2016['average'] = cols_2016.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2017['average'] = cols_2017.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2018['average'] = cols_2018.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2019['average'] = cols_2019.mean(axis=1)
/var/folders/rs/ck6nby4n2s365r7sdf740jt00000gn/T/ipykernel_1774/3034932187.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cols_2020['average'] = cols_2020.mean(axis=1)

In [8]:
cols_2017

,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,average
0,5009.0,NaN,NaN,NaN,NaN,3988.0,NaN,NaN,3661.0,NaN,NaN,NaN,4219.333333
1,2108.0,2104.0,2117.0,2118.0,2125.0,2146.0,2168.0,2183.0,2165.0,2128.0,2097.0,2070.0,2127.416667
2,NaN,NaN,NaN,NaN,NaN,4176.0,NaN,3997.0,3924.0,NaN,NaN,NaN,4032.333333
3,1765.0,1763.0,1762.0,1760.0,1752.0,1753.0,1757.0,1763.0,1777.0,1791.0,1799.0,1799.0,1770.083333
4,2313.0,2307.0,2319.0,2325.0,2338.0,2364.0,2389.0,2401.0,2391.0,2364.0,2327.0,2290.0,2344.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13176,993.0,984.0,968.0,965.0,964.0,964.0,955.0,943.0,933.0,917.0,906.0,904.0,949.666667
13177,1162.0,1154.0,1147.0,1145.0,1155.0,1172.0,1186.0,1206.0,1212.0,1215.0,1212.0,1211.0,1181.416667
13178,746.0,752.0,765.0,770.0,770.0,771.0,764.0,761.0,760.0,764.0,771.0,758.0,762.666667
13179,860.0,855.0,851.0,850.0,855.0,861.0,867.0,863.0,854.0,840.0,832.0,832.0,851.666667
13180,1263.0,1263.0,1259.0,1267.0,1272.0,1278.0,1284.0,1289.0,1300.0,1292.0,1284.0,1280.0,1277.583333

In [13]:
year_avgs = pd.DataFrame({'geo_id':df.RegionName,
             '2010':cols_2010.average,
             '2011':cols_2011.average,
             '2012':cols_2012.average,
             '2013':cols_2013.average,
             '2014':cols_2014.average,
             '2015':cols_2015.average,
             '2016':cols_2016.average,
             '2017':cols_2017.average,
             '2018':cols_2018.average,
             '2019':cols_2019.average,
             '2020':cols_2020.average})
year_avgs.head(60)

,geo_id,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,10025,3033.750000,2864.666667,2967.000000,3144.666667,3274.375000,3849.875000,4166.714286,4219.333333,3532.000000,3804.333333,NaN
1,60657,1783.750000,1787.250000,1866.833333,1955.666667,2005.666667,2073.500000,2140.416667,2127.416667,2098.333333,2085.545455,1996.0
2,10023,3303.750000,3074.250000,3073.833333,3198.250000,3322.250000,4153.600000,4670.375000,4032.333333,3835.125000,3960.222222,NaN
3,77494,1554.000000,1584.500000,1630.583333,1786.833333,1956.833333,1921.916667,1819.833333,1770.083333,1788.166667,1763.416667,1778.0
4,60614,1919.000000,1897.583333,2014.666667,2148.000000,2202.583333,2271.000000,2346.500000,2344.000000,2314.250000,2306.583333,NaN
5,77449,1185.500000,1214.200000,1155.333333,1251.166667,1361.083333,1424.000000,1423.833333,1405.000000,1432.416667,1411.250000,1443.0
6,10002,3328.250000,3289.250000,3403.916667,3523.833333,3646.142857,4374.714286,4372.800000,4033.000000,3393.200000,3716.777778,3605.0
7,77084,954.000000,1064.666667,1116.333333,1205.916667,1327.916667,1417.166667,1414.083333,1372.750000,1414.416667,1404.250000,1438.0
8,79936,1075.750000,999.166667,1005.833333,961.666667,984.916667,1014.833333,1011.916667,992.583333,973.916667,947.833333,991.0
9,60640,1423.000000,1377.916667,1412.083333,1470.833333,1518.416667,1567.583333,1604.916667,1620.333333,1620.250000,1638.250000,1651.0
10,11226,1745.333333,1637.333333,1689.416667,1869.750000,2023.090909,2070.583333,2210.166667,2168.416667,2071.333333,2139.545455,2174.0
11,10467,1432.666667,1378.250000,1306.666667,1341.833333,1369.750000,1452.000000,1545.416667,1619.916667,1623.166667,1750.909091,1842.0
12,78660,1059.500000,1034.416667,1037.000000,1102.583333,1238.333333,1343.250000,1401.833333,1410.833333,1424.833333,1462.250000,1521.0
13,94109,3125.750000,3135.416667,3375.500000,3747.083333,4123.250000,4520.250000,4492.916667,4231.416667,4245.916667,4421.083333,4406.0
14,10016,3261.000000,3171.833333,3316.500000,3475.750000,3556.500000,4143.750000,4270.200000,3932.428571,3189.166667,3306.000000,3365.0
15,37013,1126.500000,1141.833333,1162.166667,1191.083333,1222.166667,1318.666667,1371.250000,1364.666667,1372.083333,1341.000000,1337.0
16,60647,1673.000000,1593.500000,1604.083333,1671.750000,1807.833333,1899.000000,1927.916667,1915.416667,1884.416667,1882.500000,1824.0
17,11201,2414.250000,2351.583333,2573.916667,2908.500000,2838.583333,2843.666667,2902.666667,2837.000000,2732.916667,2877.833333,3045.0
18,11235,1718.250000,1612.583333,1666.916667,1799.416667,1906.636364,2026.083333,2217.416667,2170.833333,2088.250000,2093.166667,2081.0
19,11375,1508.000000,1520.000000,1584.166667,1685.083333,1821.583333,1942.250000,2069.250000,2049.333333,2042.166667,2082.083333,2115.0
20,90250,2363.500000,2317.666667,2276.250000,2309.416667,2390.583333,2550.583333,2620.666667,2665.333333,2669.583333,2606.666667,2585.0
21,78130,1166.250000,1113.083333,1181.916667,1248.833333,1259.666667,1350.583333,1392.500000,1414.500000,1395.083333,1376.583333,1385.0
22,37211,952.750000,980.500000,1059.833333,1104.500000,1203.916667,1327.333333,1393.666667,1384.500000,1367.500000,1351.500000,1374.0
23,10029,2781.000000,2772.250000,2780.454545,2879.083333,3039.666667,3570.727273,3876.777778,3509.571429,3143.777778,3213.416667,3150.0
24,10009,3544.500000,3402.500000,3461.833333,3561.250000,3650.375000,4416.833333,4648.000000,4148.571429,3391.800000,3541.200000,3416.0
25,77573,965.000000,1074.545455,1053.083333,1083.000000,1212.666667,1330.750000,1407.666667,1374.833333,1405.750000,1382.833333,1359.0
26,60618,1582.500000,1514.500000,1496.000000,1552.000000,1665.666667,1715.083333,1764.333333,1746.250000,1762.916667,1784.333333,1739.0
27,77584,1247.000000,1227.363636,1347.666667,1413.166667,1492.222222,1609.583333,1615.333333,1622.750000,1634.333333,1582.916667,1590.0
28,20002,1935.000000,1973.250000,2015.333333,2172.000000,2131.916667,2161.333333,2256.333333,2282.083333,2239.750000,2318.833333,2329.0
29,10128,3163.000000,2959.454545,3032.750000,3142.666667,3215.857143,3924.285714,4275.428571,4099.750000,3469.000000,3796.875000,3610.0
30,28269,954.500000,916.500000,936.000000,972.333333,1028.583333,1066.000000,1128.833333,1160.166667,1200.083333,1283.666667,1302.0
31,78613,1008.000000,1075.666667,1107.666667,1166.333333,1321.000000,1478.916667,1497.833333,1457.750000,1490.916667,1525.166667,1552.0
32,77433,1339.500000,1307.111111,1274.700000,1423.181818,1472.000000,1579.416667,1578.545455,1461.000000,1483.166667,1495.083333,1542.0
33,78572,855.250000,851.555556,738.000000,865.444444,972.416667,990.250000,897.666667,887.166667,872.083333,827.166667,832.0
34,30349,963.250000,960.166667,930.833333,916.333333,926.750000,945.833333,1018.000000,1083.250000,1119.166667,1169.250000,1213.0
35,79912,1251.250000,1191.545455,1181.166667,1145.666667,1136.666667,1167.000000,1169.250000,1137.416667,1131.833333,1129.500000,1176.0
36,75052,1083.000000,975.363636,962.583333,1023.083333,1095.416667,1151.750000,1228.333333,1272.166667,1306.000000,1309.000000,1327.0
37,94565,1787.500000,1679.000000,1676.583333,1716.500000,1778.500000,1924.666667,2076.250000,2122.416667,2177.000000,2270.666667,2283.0
38,37042,855.000000,799.500000,855.166667,847.916667,867.000000,879.583333,894.416667,890.416667,909.250000,880.833333,914.0
39,11206,1845.250000,1805.833333,2029.416667,2273.583333,2456.416667,2591.000000,2636.500000,2590.750000,2509.666667,2582.666667,2664.0
40,73099,964.500000,939.833333,947.444444,1090.083333,1168.333333,1196.666667,1177.083333,1154.250000,1168.333333,1149.916667,1159.0
41,90046,2678.750000,2714.250000,2751.416667,2799.833333,2906.583333,3179.416667,3237.333333,3236.333333,3185.500000,3182.333333,3212.0
42,20009,2141.750000,2382.583333,2451.833333,2550.666667,2502.250000,2503.000000,2567.166667,2598.916667,2542.250000,2589.666667,2606.0
43,77429,1393.250000,1409.500000,1329.083333,1438.600000,1494.714286,1647.000000,1639.181818,1538.083333,1506.909091,1349.727273,1350.0
44,78245,1063.333333,1067.000000,1086.416667,1067.333333,1106.083333,1171.750000,1204.083333,1222.083333,1233.333333,1252.833333,1252.0
45,77479,1392.000000,1495.500000,1537.500000,1641.583333,1784.416667,1876.166667,1844.833333,1778.083333,1791.500000,1776.666667,1768.0
46,10462,1520.666667,1356.666667,1290.000000,1297.250000,1362.166667,1449.083333,1524.181818,1615.833333,1608.166667,1669.083333,1821.0
47,10456,1351.500000,1471.000000,1439.750000,1454.083333,1433.833333,1506.083333,1572.666667,1673.500000,1693.833333,1842.818182,1936.0
48,60613,1460.500000,1480.083333,1538.416667,1607.250000,1646.000000,1678.166667,1741.750000,1732.250000,1720.916667,1720.333333,1702.0
49,30044,1081.500000,1077.750000,1075.000000,1121.000000,1171.916667,1253.916667,1317.000000,1373.833333,1396.333333,1386.333333,1435.0
50,10019,3303.750000,3148.166667,3181.583333,3313.083333,3506.666667,4137.428571,4400.875000,4146.285714,3678.555556,3796.166667,3807.0
51,63376,953.500000,1044.000000,1068.833333,1100.916667,1155.083333,1210.916667,1248.416667,1256.333333,1219.666667,1195.166667,1256.0
52,28277,1149.750000,1136.500000,1200.916667,1255.083333,1293.000000,1357.333333,1427.500000,1446.916667,1511.166667,1563.000000,1619.0
53,60625,1532.750000,1461.250000,1430.166667,1480.500000,1566.666667,1607.250000,1643.250000,1627.000000,1643.500000,1669.333333,1654.0
54,30043,1219.750000,1211.250000,1190.583333,1239.250000,1286.833333,1367.250000,1444.000000,1482.166667,1499.666667,1472.750000,1527.0
55,11230,1753.500000,1611.545455,1644.333333,1764.083333,1863.250000,1991.166667,2165.000000,2119.500000,2012.083333,2049.416667,NaN
56,11212,1494.750000,1578.000000,1644.083333,1787.416667,1944.900000,2016.333333,2182.083333,2180.333333,2083.545455,2120.363636,2183.0
57,77036,884.500000,871.250000,853.750000,894.363636,1069.090909,1168.000000,1206.166667,1177.666667,1173.416667,1169.250000,1183.0
58,10463,1516.750000,1490.500000,1487.000000,1517.333333,1552.545455,1650.833333,1747.666667,1772.000000,1834.416667,1988.083333,2034.0
59,60629,1122.500000,1181.333333,1141.750000,1159.500000,1224.333333,1253.583333,1268.666667,1281.166667,1310.916667,1314.250000,1298.0

In [12]:
year_avgs.to_csv('year_avgs.csv')

In [16]:
df_2011 = pd.read_csv('./Data/demo_zip_11.csv', dtype={'geo_id': str})
df_2012 = pd.read_csv('./Data/demo_zip_12.csv', dtype={'geo_id': str})
df_2013 = pd.read_csv('./Data/demo_zip_13.csv', dtype={'geo_id': str})
df_2014 = pd.read_csv('./Data/demo_zip_14.csv', dtype={'geo_id': str})
df_2015 = pd.read_csv('./Data/demo_zip_15.csv', dtype={'geo_id': str}).drop(columns = 'geoid') #mysterious column of all NaN
df_2016 = pd.read_csv('./Data/demo_zip_16.csv', dtype={'geo_id': str})
df_2017 = pd.read_csv('./Data/demo_zip_17.csv', dtype={'geo_id': str})
df_2018 = pd.read_csv('./Data/demo_zip_18.csv', dtype={'geo_id': str})

In [17]:
df_2011 = pd.merge(df_2011, year_avgs[['geo_id', '2011']], on='geo_id').rename(columns={'2011':'avg_rent'})
df_2012 = pd.merge(df_2012, year_avgs[['geo_id', '2012']], on='geo_id').rename(columns={'2012':'avg_rent'})
df_2013 = pd.merge(df_2013, year_avgs[['geo_id', '2013']], on='geo_id').rename(columns={'2013':'avg_rent'})
df_2014 = pd.merge(df_2014, year_avgs[['geo_id', '2014']], on='geo_id').rename(columns={'2014':'avg_rent'})
df_2015 = pd.merge(df_2015, year_avgs[['geo_id', '2015']], on='geo_id').rename(columns={'2015':'avg_rent'})
df_2016 = pd.merge(df_2016, year_avgs[['geo_id', '2016']], on='geo_id').rename(columns={'2016':'avg_rent'})
df_2017 = pd.merge(df_2017, year_avgs[['geo_id', '2017']], on='geo_id').rename(columns={'2017':'avg_rent'})
df_2018 = pd.merge(df_2018, year_avgs[['geo_id', '2018']], on='geo_id').rename(columns={'2018':'avg_rent'})

In [50]:
df_2011.to_csv('./Data_w_targets/demo_zip_11.csv')
df_2012.to_csv('./Data_w_targets/demo_zip_12.csv')
df_2013.to_csv('./Data_w_targets/demo_zip_13.csv')
df_2014.to_csv('./Data_w_targets/demo_zip_14.csv')
df_2015.to_csv('./Data_w_targets/demo_zip_15.csv')
df_2016.to_csv('./Data_w_targets/demo_zip_16.csv')
df_2017.to_csv('./Data_w_targets/demo_zip_17.csv')
df_2018.to_csv('./Data_w_targets/demo_zip_18.csv')

In [11]:
cols_2011.loc[5221, :]

2011-01    1296.00
2011-02    1301.00
2011-03    1294.00
2011-04    1299.00
2011-05    1324.00
2011-06    1340.00
2011-07    1358.00
2011-08    1336.00
2011-09    1329.00
2011-10    1342.00
2011-11    1333.00
2011-12    1351.00
average    1325.25
Name: 5221, dtype: float64

In [19]:
df_2011.loc[5221, :]

geo_id                            11960
nonfamily_households                123
family_households                   288
median_year_structure_built      1971.0
rent_burden_not_computed              3
                                 ...
pop_separated                         0
pop_widowed                          44
pop_divorced                         45
do_date                        20072011
avg_rent                        83752.0
Name: 5221, Length: 253, dtype: object

In [20]:
year_avgs[year_avgs.geo_id == "11960"]

,geo_id,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
13099,11960,24853.0,83752.0,79897.833333,NaN,NaN,27027.0,28307.333333,28130.833333,25706.636364,25259.3,NaN

In [23]:
targets[targets.RegionName == "11960"]

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
13099,62307,11960,Remsenburg,NY,New York-Newark-Jersey City,Suffolk County,13100,22971.0,NaN,26735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83894.0,83610.0,NaN,NaN,NaN,NaN,NaN,80437.0,79587.0,79106.0,79724.0,80229.0,80304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27027.0,NaN,NaN,NaN,NaN,NaN,NaN,29731.0,29601.0,28912.0,28260.0,NaN,26976.0,26364.0,NaN,27672.0,27871.0,28262.0,28281.0,28785.0,29174.0,28549.0,27854.0,27987.0,27629.0,27736.0,27770.0,27706.0,27390.0,NaN,26165.0,25726.0,25606.0,25834.0,25646.0,25121.0,24652.0,24265.0,24662.0,NaN,25910.0,25344.0,25304.0,25634.0,25901.0,25940.0,25515.0,24847.0,24859.0,NaN,23339.0,NaN