In [1]:
import pandas as pd
import requests

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
# ZORI Zip Seasonally Adjusted
zzs_url = "https://files.zillowstatic.com/research/public_csvs/zori/Zip_ZORI_AllHomesPlusMultifamily_SSA.csv?t=1638579606"
zzs_df = pd.read_csv(zzs_url)

In [4]:
zzs_df.shape

(2142, 98)

In [5]:
state_split = zzs_df['MsaName'].str.split(',', expand = True)
zzs_df.insert(3, 'City', state_split[0])
zzs_df.insert(4, 'State', state_split[1])
zzs_df.drop('MsaName', axis = 1, inplace = True)

In [22]:
zzs_df.head(2)

,RegionID,RegionName,SizeRank,City,State,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10
0,61639,10025,1,New York,NY,2855.0,2870.0,2884.0,2899.0,2913.0,2928.0,2942.0,2956.0,2970.0,2984.0,2996.0,3008.0,3021.0,3030.0,3040.0,3050.0,3057.0,3064.0,3071.0,3076.0,3082.0,3088.0,3092.0,3097.0,3101.0,3103.0,3105.0,3108.0,3107.0,3107.0,3107.0,3105.0,3103.0,3101.0,3101.0,3101.0,3101.0,3102.0,3103.0,3104.0,3105.0,3105.0,3106.0,3106.0,3107.0,3108.0,3109.0,3109.0,3110.0,3112.0,3113.0,3115.0,3120.0,3125.0,3130.0,3137.0,3143.0,3150.0,3157.0,3163.0,3170.0,3177.0,3184.0,3191.0,3197.0,3203.0,3210.0,3213.0,3217.0,3220.0,3212.0,3204.0,3196.0,3168.0,3141.0,3113.0,3075.0,3037.0,2998.0,2964.0,2930.0,2896.0,2891.0,2886.0,2881.0,2903.0,2926.0,2948.0,2975.0,3001.0,3027.0,3058.0,3089.0,3119.0
1,84654,60657,2,Chicago,IL,1315.0,1320.0,1325.0,1330.0,1334.0,1339.0,1343.0,1348.0,1352.0,1357.0,1361.0,1365.0,1370.0,1374.0,1378.0,1382.0,1386.0,1390.0,1394.0,1398.0,1402.0,1407.0,1411.0,1415.0,1419.0,1423.0,1427.0,1431.0,1434.0,1438.0,1441.0,1445.0,1448.0,1452.0,1454.0,1457.0,1460.0,1462.0,1464.0,1466.0,1468.0,1470.0,1471.0,1473.0,1474.0,1476.0,1477.0,1478.0,1480.0,1480.0,1481.0,1481.0,1481.0,1481.0,1482.0,1482.0,1483.0,1484.0,1486.0,1488.0,1491.0,1494.0,1497.0,1500.0,1504.0,1508.0,1512.0,1516.0,1519.0,1522.0,1523.0,1523.0,1524.0,1522.0,1519.0,1517.0,1513.0,1509.0,1505.0,1501.0,1497.0,1494.0,1493.0,1492.0,1491.0,1494.0,1496.0,1499.0,1503.0,1506.0,1509.0,1513.0,1516.0,1520.0

In [21]:
zzs_df.sort_values('SizeRank')[['RegionName','City', 'State','2014-01']]

      RegionName      City State  2014-01
0          10025  New York    NY   2855.0
1          60657   Chicago    IL   1315.0
2          10023  New York    NY   3049.0
3          77494   Houston    TX   1320.0
4          60614   Chicago    IL   1663.0
...          ...       ...   ...      ...
2137       85701    Tucson    AZ      NaN
2138       60606   Chicago    IL   2008.0
2139       10006  New York    NY   2936.0
2140        2109    Boston    MA      NaN
2141       11976  New York    NY  62763.0

[2142 rows x 4 columns]

In [6]:
zz_url = "https://files.zillowstatic.com/research/public_csvs/zori/Zip_ZORI_AllHomesPlusMultifamily_Smoothed.csv?t=1638579606"
zz_df = pd.read_csv(zz_url)

In [7]:
zz_df.shape

(2142, 98)

In [8]:
state_split = zz_df['MsaName'].str.split(',', expand = True)
zz_df.insert(3, 'City', state_split[0])
zz_df.insert(4, 'State', state_split[1])
zz_df.drop('MsaName', axis = 1, inplace = True)

In [9]:
zz_df.sort_values('SizeRank')[['RegionName','City', 'State','2014-01']]

      RegionName      City State   2014-01
0          10025  New York    NY    2792.0
1          60657   Chicago    IL    1242.0
2          10023  New York    NY    3088.0
3          77494   Houston    TX    1370.0
4          60614   Chicago    IL    1542.0
...          ...       ...   ...       ...
2137       85701    Tucson    AZ       NaN
2138       60606   Chicago    IL    2073.0
2139       10006  New York    NY    2671.0
2140        2109    Boston    MA       NaN
2141       11976  New York    NY  101087.0

[2142 rows x 4 columns]

In [10]:
zcta5_url = "https://www2.census.gov/geo/docs/maps-data/data/rel/zcta_tract_rel_10.txt"
zcta5_df = pd.read_csv(zcta5_url)

In [11]:
state_fips_url = "https://www2.census.gov/geo/docs/reference/state.txt"
stateID = pd.read_csv(state_fips_url, sep='|')
stateID[stateID['STUSAB'] == 'MA']

    STATE STUSAB     STATE_NAME  STATENS
21     25     MA  Massachusetts   606926

In [12]:
convert_df = pd.read_excel('ZiptoZcta2.xlsx')
convert_df[convert_df['ZIP_CODE'] == 1604]

     ZIP_CODE    PO_NAME STATE       ZIP_TYPE   ZCTA     zip_join_type
434      1604  Worcester    MA  Zip Code Area  01604  Zip matches ZCTA

In [13]:
null_columns = zz_df.columns[zz_df.isnull().any()]
null_df = pd.DataFrame(zz_df[null_columns].isnull().sum()).reset_index()
null_df = null_df.rename(columns={'index':'Feature',0:'Count'})

In [14]:
null_df.sort_values('Count', ascending = False)

    Feature  Count
2   2014-03    495
1   2014-02    319
0   2014-01    298
11  2014-12    268
10  2014-11    223
..      ...    ...
68  2019-09      6
64  2019-05      6
66  2019-07      5
67  2019-08      4
53  2018-06      3

[94 rows x 2 columns]

In [15]:
null_columns = zzs_df.columns[zzs_df.isnull().any()]
null_df = pd.DataFrame(zzs_df[null_columns].isnull().sum()).reset_index()
null_df = null_df.rename(columns={'index':'Feature',0:'Count'})

In [16]:
null_df.sort_values('Count', ascending = False)

    Feature  Count
2   2014-03    495
1   2014-02    319
0   2014-01    298
11  2014-12    268
10  2014-11    223
..      ...    ...
68  2019-09      6
64  2019-05      6
66  2019-07      5
67  2019-08      4
53  2018-06      3

[94 rows x 2 columns]

In [28]:
zri_sfdf = pd.read_csv('Zip_Zri_SinglefamilyResidenceRental.csv')
zri_sfdf.sort_values('RegionName')[['RegionName','City', 'State','2014-01']]

       RegionName         City State  2014-01
6140         1001       Agawam    MA   1407.0
4282         1002      Amherst    MA   1945.0
11841        1005        Barre    MA   1281.0
7089         1007  Belchertown    MA   1562.0
15526        1008    Blandford    MA   1250.0
...           ...          ...   ...      ...
6954        99669     Soldotna    AK   1270.0
6346        99701    Fairbanks    AK   1611.0
5704        99705   North Pole    AK   1677.0
4721        99709    Fairbanks    AK   1706.0
8864        99712    Fairbanks    AK   1654.0

[15836 rows x 4 columns]

In [42]:
zri_sfdf.dropna()

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06
0,84654,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,1,3028.0,3053.0,3039.0,2987.0,2909.0,2860.0,2833.0,2822.0,2809.0,2803.0,2804.0,2807.0,2818.0,2838.0,2850.0,2869.0,2878.0,2912.0,2931.0,2971.0,3013.0,3038.0,3073.0,3103.0,3130.0,3116.0,3091.0,3076.0,3067.0,3063.0,3072.0,3084.0,3100.0,3103.0,3109.0,3124.0,3139.0,3145.0,3128.0,3098.0,3100.0,3169.0,3263.0,3352.0,3430.0,3516.0,3572.0,3582.0,3595.0,3593.0,3586.0,3578.0,3611.0,3645.0,3677.0,3704.0,3752.0,3804.0,3845.0,3873.0,3875.0,3868.0,3834,3699,3581,3492,3479,3447,3415,3410,3407,3410,3408,3408,3385,3375,3377,3404,3464,3532,3590,3604,3604,3568,3483,3376,3293,3248,3223,3203,3209,3224,3250,3268,3279,3287,3284,3281,3270,3261,3264,3283,3268,3256
1,91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,2,2214.0,2219.0,2203.0,2193.0,2190.0,2210.0,2227.0,2240.0,2248.0,2268.0,2299.0,2339.0,2361.0,2356.0,2318.0,2268.0,2234.0,2231.0,2266.0,2318.0,2367.0,2380.0,2369.0,2334.0,2310.0,2300.0,2310.0,2323.0,2337.0,2353.0,2368.0,2383.0,2391.0,2397.0,2403.0,2422.0,2451.0,2484.0,2502.0,2508.0,2500.0,2497.0,2496.0,2501.0,2505.0,2522.0,2539.0,2551.0,2548.0,2541.0,2532.0,2521.0,2508.0,2506.0,2511.0,2523.0,2529.0,2537.0,2534.0,2529.0,2517.0,2508.0,2489,2455,2412,2380,2354,2328,2295,2266,2242,2220,2198,2173,2153,2143,2143,2147,2151,2159,2169,2176,2177,2177,2182,2191,2196,2197,2196,2196,2197,2197,2197,2196,2196,2192,2175,2155,2136,2131,2135,2146,2166,2185
2,84616,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,3,4886.0,4932.0,4905.0,4839.0,4747.0,4720.0,4722.0,4736.0,4745.0,4753.0,4784.0,4818.0,4826.0,4825.0,4792.0,4800.0,4816.0,4883.0,4942.0,5017.0,5081.0,5117.0,5161.0,5202.0,5236.0,5209.0,5173.0,5164.0,5200.0,5256.0,5293.0,5314.0,5315.0,5322.0,5325.0,5364.0,5387.0,5412.0,5385.0,5347.0,5327.0,5380.0,5465.0,5551.0,5612.0,5659.0,5658.0,5621.0,5610.0,5562.0,5542.0,5517.0,5573.0,5598.0,5626.0,5648.0,5720.0,5812.0,5891.0,5954.0,5979.0,5989.0,5902,5638,5414,5244,5263,5259,5287,5315,5328,5342,5359,5396,5441,5485,5515,5532,5545,5566,5573,5552,5497,5423,5345,5262,5185,5129,5111,5119,5118,5104,5085,5078,5085,5102,5125,5119,5093,5057,5036,5031,4859,4711
3,91940,77449,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,1292.0,1281.0,1269.0,1260.0,1256.0,1253.0,1248.0,1245.0,1241.0,1237.0,1231.0,1224.0,1220.0,1219.0,1223.0,1229.0,1235.0,1238.0,1242.0,1244.0,1247.0,1254.0,1261.0,1265.0,1263.0,1260.0,1258.0,1258.0,1265.0,1277.0,1297.0,1310.0,1324.0,1326.0,1333.0,1335.0,1339.0,1337.0,1333.0,1326.0,1323.0,1323.0,1332.0,1342.0,1356.0,1369.0,1381.0,1389.0,1394.0,1398.0,1404.0,1410.0,1413.0,1418.0,1425.0,1438.0,1450.0,1461.0,1463.0,1459.0,1452.0,1449.0,1451,1455,1461,1468,1472,1474,1472,1467,1460,1454,1449,1445,1440,1433,1425,1417,1414,1417,1427,1435,1439,1440,1441,1442,1443,1443,1443,1444,1445,1445,1445,1446,1446,1449,1457,1467,1476,1481,1484,1487,1491,1495
4,93144,79936,El Paso,TX,El Paso,El Paso County,5,1087.0,1076.0,1067.0,1058.0,1045.0,1038.0,1044.0,1054.0,1057.0,1060.0,1062.0,1062.0,1063.0,1067.0,1075.0,1082.0,1084.0,1081.0,1079.0,1080.0,1084.0,1082.0,1074.0,1058.0,1040.0,1023.0,1009.0,998.0,992.0,991.0,993.0,997.0,1007.0,1019.0,1030.0,1033.0,1029.0,1021.0,1014.0,1013.0,1013.0,1017.0,1018.0,1018.0,1023.0,1028.0,1029.0,1023.0,1018.0,1015.0,1016.0,1020.0,1024.0,1029.0,1036.0,1047.0,1060.0,1072.0,1078.0,1077.0,1070.0,1059.0,1048,1036,1024,1015,1008,1008,1012,1021,1026,1020,1008,996,991,989,988,987,988,992,997,1003,1008,1009,1008,1005,1002,999,997,995,994,994,994,994,994,996,1003,1013,1023,1028,1030,1031,1032,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15828,79948,49793,Trout Lake,MI,Sault Ste. Marie,Chippewa County,15829,1094.0,1086.0,1070.0,1057.0,1035.0,1016.0,1017.0,1025.0,1034.0,1029.0,1019.0,983.0,933.0,880.0,863.0,853.0,847.0,821.0,797.0,774.0,761.0,781.0,819.0,888.0,940.0,1001.0,1014.0,1006.0,968.0,949.0,903.0,848.0,787.0,763.0,748.0,770.0,813.0,878.0,914.0,941.0,940.0,930.0,909.0,892.0,876.0,877.0,876.0,880.0,869.0,863.0,853.0,865.0,878.0,892.0,871.0,846.0,828.0,842.0,867.0,897.0,909.0,915.0,921,933,937,923,903,893,894,896,896,896,890,884,877,875,870,861,854,849,851,860,872,884,886,879,865,853,849,849,849,849,849,849,849,855,869,885,895,896,895,898,904,914
15829,85958,63140,Kinloch,MO,St. Louis,Saint Louis County,15830,741.0,746.0,752.0,756.0,758.0,761.0,766.0,772.0,786.0,807.0,828.0,842.0,847.0,841.0,833.0,822.0,818.0,820.0,826.0,833.0,835.0,834.0,829.0,827.0,822.0,819.0,814.0,811.0,810.0,814.0,819.0,823.0,827.0,828.0,830.0,832.0,835.0,838.0,837.0,833.0,826.0,821.0,821.0,824.0,822.0,818.0,809.0,800.0,790.0,786.0,786.0,791.0,793.0,794.0,792.0,791.0,792.0,792.0,786.0,780.0,780.0,784.0,784,778,770,769,772,776,776,772,769,766,767,768,772,776,781,785,787,785,778,769,760,754,750,750,749,749,749,749,749,749,749,749,749,752,765,781,794,796,797,799,799,798
15831,99032,97028,Rhododendron,OR,Portland-Vancouver-Hillsboro,Clackamas County,15832,1195.0,1195.0,1209.0,1217.0,1221.0,1211.0,1215.0,1243.0,1281.0,1306.0,1310.0,1301.0,1295.0,1278.0,1272.0,1258.0,1270.0,1280.0,1303.0,1324.0,1330.0,1333.0,1319.0,1312.0,1300.0,1293.0,1289.0,1283.0,1283.0,1297.0,1314.0,1336.0,1342.0,1351.0,1363.0,1382.0,1397.0,1396.0,1392.0,1381.0,1363.0,1361.0,1362.0,1386.0,1400.0,1424.0,1431.0,1438.0,1450.0,1468.0,1487.0,1498.0,1502.0,1511.0,1521.0,1531.0,1546.0,1579.0,1616.0,1637.0,1645.0,1656.0,1695,1709,1723,1727,1755,1781,1791,1805,1814,1804,1773,1741,1716,1704,1691,1688,1687,1701,1723,1756,1786,1807,1823,1823,1812,1783,1755,1729,1711,1699,1694,1693,1693,1697,1731,1766,1799,1803,1806,1807,1808,1819
15834,58333,1338,Buckland,MA,Greenfield Town,Franklin County,15835,1431.0,1413.0,1403.0,1415.0,1425.0,1441.0,1455.0,1482.0,1517.0,1526.0,1517.0,1477.0,1464.0,1451.0,1456.0,1450.0,1454.0,1472.0,1523.0,1578.0,1623.0,1622.0,1603.0,1571.0,1547.0,1532.0,1531.0,1530.0,1527.0,1508.0,1510.0,1516.0,1549.0,1595.0,1632.0,1643.0,1622.0,1602.0,1586.0,1574.0,1573.0,1578.0,1581.0,1583.0,1602.0,1618.0,1641.0,1638.0,1635.0,1621.0,1619.0,1629.0,1643.0,1677.0,1730.0,1771.0,1795.0,1778.0,1764.0,1733.0,1704.0,1676.0,1657,1662,1676,1708,1743,1783,1813,1822,1815,1797,1774,1756,1750,1749,1759,1770,1790,1811,1834,1846,1845,1838,1835,1826,1813,1801,1798,1798,1801,1802,1804,1805,1807,1808,1827,1854,1883,1881,1859,1832,1771,1754
15835,66881,21405,Annapolis,MD,Baltimore-Columbia-Towson,Anne Arundel County,15836,3189.0,3177.0,3190.0,3211.0,3229.0,3227.0,3234.0,3259.0,3309.0,3358.0,3393.0,3417.0,3448.0,3470.0,3499.0,3502.0,3515.0,3522.0,3547.0,3570.0,3584.0,3581.0,3538.0,3460.0,3370.0,3287.0,3243.0,3187.0,3165.0,3158.0,3212.0,3294.0,3380.0,3444.0,3483.0,3496.0,3490.0,3468.0,3454.0,3418.0,3370.0,3326.0,3337.0,3364.0,3408.0,3444.0,3479.0,3487.0,3482.0,3502.0,3537.0,3584.0,3606.0,3609.0,3602.0,3605.0,3606.0,3637.0,3683.0,3763.0,3858.0,3976.0,4095,4096,4072,4001,4020,4022,4052,4086,4097,4060,3920,3733,3546,3443,3409,3410,3419,3435,3456,3476,3476,3458,3420,3390,3357,3349,3331,3326,3321,3355,3409,3459,3483,3496,3508,3501,3476,3431,3376,3321,3115,2950

In [29]:
zri_mfdf = pd.read_csv('Zip_Zri_MultifamilyResidenceRental.csv')
zri_mfdf.sort_values('RegionName')[['RegionName','City', 'State','2014-01']]

      RegionName              City State  2014-01
1497        1013          Chicopee    MA    928.0
1139        1020          Chicopee    MA    933.0
865         1040           Holyoke    MA    976.0
792         1085         Westfield    MA      NaN
1243        1089  West Springfield    MA      NaN
...          ...               ...   ...      ...
1651       99501         Anchorage    AK      NaN
811        99504         Anchorage    AK   1533.0
1202       99508         Anchorage    AK   1314.0
1336       99654           Wasilla    AK      NaN
1717       99701         Fairbanks    AK      NaN

[1861 rows x 4 columns]

In [30]:
zri_alldf = pd.read_csv('Zip_Zri_AllHomesPlusMultifamily.csv')
zri_alldf.sort_values('RegionName')[['RegionName','City', 'State','2014-01']]

       RegionName         City State  2014-01
6034         1001       Agawam    MA   1206.0
4248         1002      Amherst    MA   1889.0
11441        1005        Barre    MA   1150.0
6900         1007  Belchertown    MA   1359.0
11937        1010    Brimfield    MA   1180.0
...           ...          ...   ...      ...
5559        99705   North Pole    AK   1334.0
4649        99709    Fairbanks    AK   1335.0
8615        99712    Fairbanks    AK      NaN
4150        99801       Juneau    AK      NaN
7470        99901    Ketchikan    AK      NaN

[13181 rows x 4 columns]

In [43]:
zri_alldf

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
0,61639,10025,New York,NY,New York-Newark-Jersey City,New York County,1,3031.0,3058.0,3031.0,3015.0,2976.0,2914.0,2860.0,2811.0,2792.0,2799.0,2820.0,2852.0,2885.0,2905.0,2883.0,2879.0,2905.0,2916.0,2908.0,2915.0,2920.0,2920.0,2938.0,2999.0,3029.0,3022.0,3049.0,3083.0,3086.0,3072.0,3081.0,3095.0,3147.0,3190.0,3188.0,3149.0,3149.0,3174.0,3175.0,3230.0,3267.0,3285.0,3234.0,3296.0,3357.0,3366.0,NaN,3186.0,3204.0,NaN,NaN,NaN,3682.0,3767.0,3767.0,3811.0,3793.0,3894.0,3919.0,NaN,NaN,NaN,NaN,4166.0,4164.0,4133.0,4015.0,3943.0,3945.0,4051.0,NaN,NaN,NaN,NaN,4916.0,NaN,5009.0,NaN,NaN,NaN,NaN,3988.0,NaN,NaN,3661.0,NaN,NaN,NaN,NaN,3512.0,3552.0,NaN,3768.0,3731.0,3634.0,NaN,NaN,3300.0,3227.0,NaN,NaN,NaN,NaN,3785.0,3788.0,3786.0,3784.0,3766.0,3779.0,3843.0,3873.0,3835.0,NaN
1,84654,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,1790.0,1787.0,1784.0,1774.0,1755.0,1742.0,1735.0,1741.0,1742.0,1757.0,1790.0,1817.0,1839.0,1841.0,1844.0,1844.0,1820.0,1818.0,1829.0,1843.0,1860.0,1878.0,1898.0,1889.0,1890.0,1894.0,1897.0,1886.0,1884.0,1887.0,1907.0,1918.0,1925.0,1948.0,1996.0,2017.0,2011.0,2002.0,1989.0,1984.0,1979.0,1976.0,1969.0,1989.0,1996.0,2001.0,2006.0,2009.0,2032.0,2045.0,2038.0,2028.0,2016.0,2028.0,2033.0,2027.0,2041.0,2071.0,2100.0,2136.0,2139.0,2119.0,2093.0,2079.0,2061.0,2058.0,2079.0,2100.0,2115.0,2150.0,2184.0,2201.0,2212.0,2207.0,2182.0,2136.0,2108.0,2104.0,2117.0,2118.0,2125.0,2146.0,2168.0,2183.0,2165.0,2128.0,2097.0,2070.0,2057.0,2052.0,2054.0,2061.0,2074.0,2106.0,2134.0,2146.0,2155.0,2149.0,2116.0,2076.0,2025.0,2014.0,2017.0,2039.0,2070.0,2105.0,2140.0,2168.0,2185.0,2125.0,NaN,2053.0,1996.0
2,61637,10023,New York,NY,New York-Newark-Jersey City,New York County,3,3269.0,3304.0,3320.0,3322.0,3283.0,3225.0,3133.0,3086.0,3017.0,3005.0,3010.0,3016.0,3028.0,3069.0,3020.0,2999.0,2988.0,3023.0,3037.0,3055.0,3069.0,3058.0,3065.0,3104.0,3117.0,3118.0,3124.0,3128.0,3098.0,3078.0,3119.0,3150.0,3183.0,3227.0,3233.0,3199.0,3217.0,3255.0,3274.0,3346.0,3357.0,3363.0,3287.0,3312.0,3385.0,3385.0,NaN,3231.0,3258.0,NaN,NaN,NaN,NaN,4011.0,3985.0,4026.0,4012.0,NaN,NaN,NaN,NaN,NaN,NaN,4734.0,4800.0,4690.0,4693.0,NaN,4418.0,4534.0,NaN,4753.0,4687.0,4788.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4176.0,NaN,3997.0,3924.0,NaN,NaN,NaN,NaN,3802.0,3809.0,3900.0,3999.0,4043.0,3957.0,NaN,NaN,3611.0,3560.0,NaN,NaN,NaN,3928.0,3874.0,3898.0,3917.0,3929.0,3931.0,3963.0,NaN,4123.0,4079.0,NaN
3,91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,1547.0,1549.0,1560.0,1560.0,1542.0,1547.0,1559.0,1578.0,1591.0,1597.0,1604.0,1609.0,1607.0,1598.0,1591.0,1591.0,1606.0,1614.0,1617.0,1612.0,1611.0,1617.0,1630.0,1640.0,1649.0,1655.0,1658.0,1658.0,1661.0,1675.0,1698.0,1727.0,1753.0,1771.0,1789.0,1808.0,1852.0,1882.0,1906.0,1920.0,1930.0,1936.0,1931.0,1925.0,1929.0,1935.0,1953.0,1967.0,1984.0,1994.0,1999.0,1999.0,1945.0,1917.0,1906.0,1903.0,1908.0,1919.0,1933.0,1944.0,1931.0,1924.0,1918.0,1915.0,1881.0,1859.0,1839.0,1828.0,1827.0,1826.0,1830.0,1826.0,1801.0,1782.0,1772.0,1767.0,1765.0,1763.0,1762.0,1760.0,1752.0,1753.0,1757.0,1763.0,1777.0,1791.0,1799.0,1799.0,1796.0,1791.0,1791.0,1789.0,1787.0,1790.0,1795.0,1790.0,1787.0,1782.0,1779.0,1781.0,1774.0,1773.0,1769.0,1765.0,1755.0,1751.0,1752.0,1754.0,1759.0,1764.0,1769.0,1776.0,1778.0
4,84616,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,1922.0,1925.0,1921.0,1908.0,1870.0,1841.0,1825.0,1823.0,1829.0,1850.0,1894.0,1937.0,1966.0,1977.0,1982.0,1977.0,1950.0,1945.0,1956.0,1980.0,1989.0,2012.0,2021.0,2021.0,2035.0,2076.0,2093.0,2098.0,2114.0,2123.0,2119.0,2113.0,2096.0,2108.0,2153.0,2189.0,2192.0,2190.0,2186.0,2193.0,2169.0,2156.0,2145.0,2167.0,2182.0,2191.0,2204.0,2222.0,2247.0,2253.0,2254.0,2241.0,2227.0,2232.0,2233.0,2219.0,2230.0,2262.0,2291.0,2331.0,2338.0,2318.0,2293.0,2278.0,2255.0,2265.0,2291.0,2312.0,2330.0,2356.0,2386.0,2405.0,2421.0,2413.0,2382.0,2342.0,2313.0,2307.0,2319.0,2325.0,2338.0,2364.0,2389.0,2401.0,2391.0,2364.0,2327.0,2290.0,2277.0,2282.0,2290.0,2306.0,2312.0,2333.0,2358.0,2353.0,2360.0,2344.0,2296.0,2260.0,2204.0,2199.0,2213.0,2245.0,2289.0,2332.0,2372.0,2398.0,2412.0,2348.0,2356.0,2311.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13176,68966,26291,Snowshoe,WV,NaN,Pocahontas County,13177,946.0,NaN,NaN,NaN,NaN,1004.0,987.0,970.0,959.0,941.0,944.0,951.0,962.0,953.0,941.0,918.0,890.0,914.0,926.0,934.0,927.0,921.0,926.0,NaN,984.0,995.0,1006.0,1022.0,1021.0,994.0,968.0,954.0,959.0,973.0,992.0,1003.0,996.0,977.0,NaN,935.0,928.0,925.0,918.0,916.0,920.0,928.0,942.0,948.0,NaN,1007.0,1007.0,1004.0,1002.0,1002.0,1006.0,1003.0,1016.0,1036.0,1047.0,1057.0,1068.0,1083.0,1066.0,1050.0,1042.0,1034.0,1028.0,1026.0,1022.0,1015.0,1022.0,1019.0,1029.0,1024.0,1010.0,988.0,993.0,984.0,968.0,965.0,964.0,964.0,955.0,943.0,933.0,917.0,906.0,904.0,901.0,897.0,898.0,897.0,901.0,902.0,913.0,933.0,944.0,944.0,938.0,953.0,961.0,965.0,966.0,965.0,959.0,956.0,958.0,956.0,951.0,932.0,928.0,930.0,923.0
13177,62697,12720,Bethel,NY,NaN,Sullivan County,13178,1372.0,1390.0,1417.0,1417.0,1419.0,NaN,NaN,NaN,NaN,1150.0,1150.0,1165.0,1179.0,1189.0,1184.0,1165.0,1149.0,1134.0,1128.0,1113.0,1100.0,1104.0,NaN,1171.0,1188.0,1200.0,1197.0,1190.0,1194.0,1192.0,1199.0,1198.0,1200.0,1206.0,1214.0,1214.0,1214.0,1201.0,1187.0,1183.0,1192.0,1196.0,1214.0,1218.0,1213.0,1210.0,1214.0,1213.0,1201.0,1210.0,1219.0,1217.0,1196.0,NaN,1113.0,1092.0,1091.0,1108.0,1125.0,1131.0,1150.0,1159.0,1161.0,1152.0,1158.0,1176.0,1187.0,1201.0,1212.0,1208.0,1198.0,1202.0,1206.0,1208.0,1207.0,1195.0,1162.0,1154.0,1147.0,1145.0,1155.0,1172.0,1186.0,1206.0,1212.0,1215.0,1212.0,1211.0,1209.0,1211.0,1232.0,1241.0,1256.0,1275.0,1276.0,1276.0,1276.0,1288.0,1290.0,1305.0,1291.0,1281.0,1272.0,1279.0,1284.0,1288.0,1295.0,1294.0,1305.0,NaN,1348.0,1310.0,1272.0
13178,68924,26209,Snowshoe,WV,NaN,Pocahontas County,13179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,697.0,700.0,695.0,688.0,681.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,765.0,763.0,772.0,776.0,NaN,NaN,NaN,735.0,733.0,734.0,731.0,740.0,734.0,732.0,728.0,729.0,729.0,732.0,735.0,746.0,752.0,765.0,770.0,770.0,771.0,764.0,761.0,760.0,764.0,771.0,758.0,756.0,768.0,782.0,796.0,782.0,775.0,764.0,759.0,755.0,750.0,747.0,NaN,NaN,739.0,730.0,728.0,727.0,725.0,724.0,745.0,762.0,779.0,NaN,NaN,765.0
13179,75924,41101,Ashland,KY,Huntington-Ashland,Boyd County,13180,758.0,754.0,760.0,761.0,761.0,764.0,767.0,765.0,760.0,762.0,779.0,789.0,793.0,803.0,816.0,829.0,824.0,819.0,818.0,819.0,834.0,843.0,849.0,854.0,868.0,876.0,879.0,870.0,856.0,843.0,832.0,827.0,823.0,825.0,826.0,829.0,831.0,830.0,835.0,836.0,838.0,839.0,836.0,831.0,828.0,826.0,834.0,842.0,845.0,840.0,838.0,837.0,841.0,842.0,841.0,841.0,845.0,845.0,837.0,841.0,844.0,862.0,863.0,861.0,859.0,855.0,853.0,852.0,859.0,865.0,869.0,876.0,876.0,874.0,873.0,870.0,860.0,855.0,851.0,850.0,855.0,861.0,867.0,863.0,854.0,840.0,832.0,832.0,829.0,831.0,851.0,872.0,880.0,870.0,863.0,858.0,856.0,851.0,857.0,853.0,861.0,861.0,857.0,852.0,850.0,847.0,842.0,836.0,836.0,829.0,853.0,828.0,815.0
13180,95851,89155,Las Vegas,NV,Las Vegas-Henderson-Paradise,Clark County,13181,1087.0,1098.0,1104.0,1110.0,1113.0,1111.0,1108.0,1106.0,1102.0,1099.0,1089.0,1092.0,1085.0,1085.0,1086.0,1085.0,1090.0,1093.0,1093.0,1093.0,1093.0,1093.0,1094.0,1090.0,1082.0,1082.0,1078.0,1074.0,1073.0,1076.0,1079.0,1086.0,1093.0,1098.0,1102.0,1104.0,1108.0,1111.0,1140.0,1122.0,1135.0,1141.0,1141.0,1135.0,1121.0,1115.0,1124.0,1134.0,1149.0,1159.0,1169.0,1169.0,1174.0,1178.0,1176.0,1185.0,1195.0,1201.0,1207.0,1216.0,1221.0,1223.0,1226.0,1232.0,1236.0,1239.0,1240.0,1241.0,1247.0,1254.0,1259.0,1263.0,1268.0,1268.0,1270.0,1268.0,1263.0,1263.0,1259.0,1267.0,1272.0,1278.0,1284.0,1289.0,1300.0,1292.0,1284.0,1280.0,1280.0,1284.0,1286.0,1290.0,1297.0,1301.0,1303.0,1306.0,1306.0,1312.0,1314.0,1313.0,1309.0,1308.0,1307.0,1309.0,1316.0,1324.0,1332.0,1340.0,1369.0,1406.0,1430.0,1441.0,1429.0

In [45]:
zri_alldf.dropna()

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01
3,91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,1547.0,1549.0,1560.0,1560.0,1542.0,1547.0,1559.0,1578.0,1591.0,1597.0,1604.0,1609.0,1607.0,1598.0,1591.0,1591.0,1606.0,1614.0,1617.0,1612.0,1611.0,1617.0,1630.0,1640.0,1649.0,1655.0,1658.0,1658.0,1661.0,1675.0,1698.0,1727.0,1753.0,1771.0,1789.0,1808.0,1852.0,1882.0,1906.0,1920.0,1930.0,1936.0,1931.0,1925.0,1929.0,1935.0,1953.0,1967.0,1984.0,1994.0,1999.0,1999.0,1945.0,1917.0,1906.0,1903.0,1908.0,1919.0,1933.0,1944.0,1931.0,1924.0,1918.0,1915.0,1881.0,1859.0,1839.0,1828.0,1827.0,1826.0,1830.0,1826.0,1801.0,1782.0,1772.0,1767.0,1765.0,1763.0,1762.0,1760.0,1752.0,1753.0,1757.0,1763.0,1777.0,1791.0,1799.0,1799.0,1796.0,1791.0,1791.0,1789.0,1787.0,1790.0,1795.0,1790.0,1787.0,1782.0,1779.0,1781.0,1774.0,1773.0,1769.0,1765.0,1755.0,1751.0,1752.0,1754.0,1759.0,1764.0,1769.0,1776.0,1778.0
8,93144,79936,El Paso,TX,El Paso,El Paso County,9,1060.0,1084.0,1082.0,1077.0,1071.0,1045.0,1019.0,996.0,980.0,976.0,977.0,979.0,981.0,986.0,988.0,992.0,1003.0,1015.0,1027.0,1030.0,1031.0,1023.0,1015.0,1003.0,993.0,984.0,976.0,970.0,960.0,955.0,952.0,950.0,951.0,956.0,960.0,964.0,971.0,974.0,975.0,972.0,971.0,971.0,973.0,974.0,975.0,976.0,986.0,994.0,999.0,1002.0,1002.0,996.0,989.0,986.0,986.0,988.0,997.0,1009.0,1024.0,1039.0,1045.0,1047.0,1041.0,1027.0,1023.0,1022.0,1016.0,1010.0,1006.0,1007.0,1010.0,1011.0,1015.0,1014.0,1008.0,1001.0,994.0,989.0,986.0,989.0,993.0,998.0,1000.0,997.0,995.0,992.0,990.0,988.0,984.0,981.0,979.0,970.0,966.0,965.0,971.0,976.0,977.0,977.0,973.0,968.0,956.0,948.0,943.0,938.0,936.0,938.0,940.0,943.0,944.0,949.0,962.0,977.0,991.0
9,84640,60640,Chicago,IL,Chicago-Naperville-Elgin,Cook County,10,1432.0,1431.0,1421.0,1408.0,1388.0,1371.0,1364.0,1359.0,1359.0,1364.0,1376.0,1377.0,1386.0,1389.0,1402.0,1400.0,1384.0,1382.0,1390.0,1393.0,1400.0,1403.0,1415.0,1430.0,1439.0,1440.0,1430.0,1439.0,1433.0,1422.0,1428.0,1441.0,1455.0,1471.0,1491.0,1501.0,1511.0,1503.0,1499.0,1495.0,1492.0,1491.0,1489.0,1504.0,1516.0,1523.0,1522.0,1519.0,1532.0,1543.0,1547.0,1543.0,1544.0,1545.0,1539.0,1538.0,1541.0,1556.0,1571.0,1589.0,1597.0,1602.0,1599.0,1590.0,1577.0,1569.0,1567.0,1582.0,1599.0,1617.0,1628.0,1629.0,1630.0,1628.0,1622.0,1611.0,1605.0,1600.0,1606.0,1617.0,1623.0,1637.0,1641.0,1639.0,1632.0,1627.0,1614.0,1603.0,1589.0,1590.0,1594.0,1598.0,1602.0,1621.0,1637.0,1652.0,1653.0,1646.0,1643.0,1618.0,1616.0,1615.0,1619.0,1626.0,1636.0,1642.0,1648.0,1654.0,1655.0,1664.0,1639.0,1645.0,1651.0
12,92593,78660,Pflugerville,TX,Austin-Round Rock,Travis County,13,1082.0,1065.0,1052.0,1039.0,1030.0,1023.0,1020.0,1014.0,1020.0,1032.0,1045.0,1048.0,1040.0,1044.0,1046.0,1051.0,1042.0,1035.0,1025.0,1019.0,1026.0,1035.0,1036.0,1037.0,1033.0,1043.0,1051.0,1062.0,1072.0,1073.0,1070.0,1078.0,1081.0,1090.0,1097.0,1109.0,1123.0,1135.0,1146.0,1157.0,1173.0,1180.0,1189.0,1198.0,1210.0,1217.0,1239.0,1260.0,1284.0,1297.0,1304.0,1309.0,1314.0,1314.0,1317.0,1320.0,1324.0,1334.0,1346.0,1354.0,1363.0,1374.0,1378.0,1381.0,1384.0,1389.0,1390.0,1386.0,1390.0,1397.0,1399.0,1405.0,1424.0,1428.0,1421.0,1409.0,1405.0,1404.0,1408.0,1409.0,1414.0,1416.0,1423.0,1421.0,1418.0,1409.0,1402.0,1401.0,1407.0,1412.0,1412.0,1420.0,1427.0,1431.0,1427.0,1429.0,1425.0,1432.0,1437.0,1439.0,1445.0,1442.0,1440.0,1438.0,1440.0,1445.0,1456.0,1468.0,1475.0,1477.0,1494.0,1527.0,1521.0
13,97564,94109,San Francisco,CA,San Francisco-Oakland-Hayward,San Francisco County,14,3135.0,3114.0,3118.0,3136.0,3136.0,3112.0,3089.0,3069.0,3042.0,3049.0,3074.0,3138.0,3191.0,3214.0,3243.0,3268.0,3275.0,3284.0,3321.0,3342.0,3359.0,3396.0,3443.0,3453.0,3430.0,3399.0,3381.0,3423.0,3494.0,3548.0,3585.0,3626.0,3663.0,3717.0,3763.0,3808.0,3848.0,3904.0,3973.0,4036.0,4047.0,4053.0,4055.0,4058.0,4062.0,4068.0,4107.0,4146.0,4173.0,4198.0,4234.0,4278.0,4319.0,4351.0,4386.0,4434.0,4465.0,4497.0,4549.0,4609.0,4649.0,4672.0,4669.0,4643.0,4617.0,4599.0,4566.0,4545.0,4519.0,4491.0,4481.0,4471.0,4460.0,4430.0,4391.0,4345.0,4306.0,4283.0,4260.0,4238.0,4233.0,4223.0,4220.0,4217.0,4217.0,4204.0,4192.0,4184.0,4188.0,4185.0,4197.0,4202.0,4201.0,4227.0,4242.0,4261.0,4284.0,4315.0,4323.0,4326.0,4365.0,4376.0,4381.0,4399.0,4425.0,4437.0,4449.0,4458.0,4455.0,4461.0,4416.0,4431.0,4406.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13072,96854,92391,Lake Arrowhead,CA,Riverside-San Bernardino-Ontario,San Bernardino County,13073,1139.0,1163.0,1180.0,1201.0,1215.0,1225.0,1230.0,1227.0,1224.0,1222.0,1215.0,1212.0,1206.0,1195.0,1179.0,1166.0,1161.0,1158.0,1156.0,1157.0,1156.0,1146.0,1133.0,1126.0,1132.0,1140.0,1151.0,1156.0,1159.0,1159.0,1154.0,1145.0,1138.0,1131.0,1129.0,1137.0,1142.0,1150.0,1163.0,1181.0,1190.0,1194.0,1179.0,1160.0,1150.0,1136.0,1138.0,1139.0,1140.0,1138.0,1146.0,1151.0,1156.0,1167.0,1176.0,1191.0,1200.0,1211.0,1223.0,1233.0,1239.0,1246.0,1256.0,1261.0,1268.0,1270.0,1271.0,1271.0,1269.0,1267.0,1261.0,1262.0,1265.0,1273.0,1288.0,1311.0,1332.0,1344.0,1343.0,1345.0,1342.0,1347.0,1359.0,1359.0,1368.0,1375.0,1388.0,1402.0,1409.0,1415.0,1419.0,1427.0,1433.0,1456.0,1471.0,1470.0,1474.0,1487.0,1492.0,1495.0,1493.0,1489.0,1488.0,1495.0,1497.0,1502.0,1505.0,1507.0,1506.0,1510.0,1527.0,1526.0,1518.0
13097,96639,92091,Rancho Santa Fe,CA,San Diego-Carlsbad,San Diego County,13098,3643.0,3604.0,3562.0,3550.0,3528.0,3510.0,3520.0,3533.0,3557.0,3580.0,3575.0,3532.0,3499.0,3437.0,3384.0,3354.0,3345.0,3326.0,3301.0,3318.0,3342.0,3371.0,3391.0,3384.0,3353.0,3328.0,3302.0,3275.0,3263.0,3279.0,3294.0,3337.0,3411.0,3475.0,3507.0,3533.0,3543.0,3565.0,3601.0,3540.0,3535.0,3532.0,3550.0,3514.0,3477.0,3476.0,3510.0,3531.0,3566.0,3607.0,3626.0,3653.0,3671.0,3681.0,3691.0,3693.0,3702.0,3719.0,3720.0,3723.0,3756.0,3789.0,3790.0,3765.0,3727.0,3713.0,3727.0,3732.0,3751.0,3791.0,3796.0,3797.0,3797.0,3781.0,3761.0,3737.0,3725.0,3722.0,3713.0,3725.0,3746.0,3762.0,3785.0,3810.0,3833.0,3826.0,3820.0,3784.0,3757.0,3748.0,3769.0,3771.0,3778.0,3801.0,3766.0,3761.0,3766.0,3747.0,3731.0,3763.0,3777.0,3764.0,3762.0,3755.0,3762.0,3799.0,3792.0,3797.0,3766.0,3702.0,3709.0,3699.0,3690.0
13133,92179,77982,Port O Connor,TX,Port Lavaca,Calhoun County,13134,1134.0,1133.0,1150.0,1151.0,1155.0,1153.0,1160.0,1160.0,1160.0,1158.0,1160.0,1174.0,1169.0,1163.0,1147.0,1128.0,1109.0,1097.0,1086.0,1084.0,1090.0,1087.0,1084.0,1087.0,1084.0,1073.0,1056.0,1058.0,1062.0,1067.0,1073.0,1077.0,1094.0,1096.0,1119.0,1127.0,1158.0,1185.0,1207.0,1216.0,1218.0,1218.0,1216.0,1235.0,1252.0,1260.0,1273.0,1289.0,1289.0,1303.0,1308.0,1320.0,1320.0,1323.0,1330.0,1332.0,1346.0,1352.0,1363.0,1372.0,1378.0,1354.0,1348.0,1342.0,1339.0,1336.0,1328.0,1336.0,1349.0,1368.0,1386.0,1395.0,1394.0,1391.0,1393.0,1386.0,1365.0,1360.0,1358.0,1347.0,1352.0,1364.0,1355.0,1350.0,1340.0,1353.0,1376.0,1360.0,1360.0,1356.0,1361.0,1365.0,1359.0,1352.0,1333.0,1321.0,1310.0,1307.0,1312.0,1328.0,1350.0,1352.0,1342.0,1338.0,1340.0,1344.0,1353.0,1356.0,1357.0,1356.0,1386.0,1391.0,1403.0
13179,75924,41101,Ashland,KY,Huntington-Ashland,Boyd County,13180,758.0,754.0,760.0,761.0,761.0,764.0,767.0,765.0,760.0,762.0,779.0,789.0,793.0,803.0,816.0,829.0,824.0,819.0,818.0,819.0,834.0,843.0,849.0,854.0,868.0,876.0,879.0,870.0,856.0,843.0,832.0,827.0,823.0,825.0,826.0,829.0,831.0,830.0,835.0,836.0,838.0,839.0,836.0,831.0,828.0,826.0,834.0,842.0,845.0,840.0,838.0,837.0,841.0,842.0,841.0,841.0,845.0,845.0,837.0,841.0,844.0,862.0,863.0,861.0,859.0,855.0,853.0,852.0,859.0,865.0,869.0,876.0,876.0,874.0,873.0,870.0,860.0,855.0,851.0,850.0,855.0,861.0,867.0,863.0,854.0,840.0,832.0,832.0,829.0,831.0,851.0,872.0,880.0,870.0,863.0,858.0,856.0,851.0,857.0,853.0,861.0,861.0,857.0,852.0,850.0,847.0,842.0,836.0,836.0,829.0,853.0,828.0,815.0
13180,95851,89155,Las Vegas,NV,Las Vegas-Henderson-Paradise,Clark County,13181,1087.0,1098.0,1104.0,1110.0,1113.0,1111.0,1108.0,1106.0,1102.0,1099.0,1089.0,1092.0,1085.0,1085.0,1086.0,1085.0,1090.0,1093.0,1093.0,1093.0,1093.0,1093.0,1094.0,1090.0,1082.0,1082.0,1078.0,1074.0,1073.0,1076.0,1079.0,1086.0,1093.0,1098.0,1102.0,1104.0,1108.0,1111.0,1140.0,1122.0,1135.0,1141.0,1141.0,1135.0,1121.0,1115.0,1124.0,1134.0,1149.0,1159.0,1169.0,1169.0,1174.0,1178.0,1176.0,1185.0,1195.0,1201.0,1207.0,1216.0,1221.0,1223.0,1226.0,1232.0,1236.0,1239.0,1240.0,1241.0,1247.0,1254.0,1259.0,1263.0,1268.0,1268.0,1270.0,1268.0,1263.0,1263.0,1259.0,1267.0,1272.0,1278.0,1284.0,1289.0,1300.0,1292.0,1284.0,1280.0,1280.0,1284.0,1286.0,1290.0,1297.0,1301.0,1303.0,1306.0,1306.0,1312.0,1314.0,1313.0,1309.0,1308.0,1307.0,1309.0,1316.0,1324.0,1332.0,1340.0,1369.0,1406.0,1430.0,1441.0,1429.0

In [33]:
null_columns = zri_alldf.columns[zri_alldf.isnull().any()]
null_df = pd.DataFrame(zri_alldf[null_columns].isnull().sum()).reset_index()
null_df = null_df.rename(columns={'index':'Feature',0:'Count'})

In [40]:
null_df.sort_values('Count', ascending = False).head(50)

     Feature  Count
2    2010-10   3851
3    2010-11   2742
4    2010-12   2595
5    2011-01   2588
7    2011-03   2572
6    2011-02   2523
8    2011-04   2373
1    2010-09   2344
14   2011-10   2303
16   2011-12   2196
15   2011-11   2190
17   2012-01   2187
13   2011-09   2159
35   2013-07   2074
21   2012-05   2074
39   2013-11   2056
23   2012-07   2056
11   2011-07   2045
22   2012-06   2043
9    2011-05   2035
12   2011-08   2034
36   2013-08   2015
19   2012-03   2005
20   2012-04   2003
41   2014-01   2002
18   2012-02   1988
10   2011-06   1985
38   2013-10   1979
40   2013-12   1977
24   2012-08   1970
37   2013-09   1963
34   2013-06   1952
29   2013-01   1951
31   2013-03   1906
26   2012-10   1869
101  2019-01   1869
28   2012-12   1867
33   2013-05   1862
25   2012-09   1855
110  2019-10   1845
30   2013-02   1827
27   2012-11   1821
32   2013-04   1811
49   2014-09   1469
48   2014-08   1467
111  2019-11   1459
47   2014-07   1364
113  2020-01   1300
0      Metro   1238
50   2014-10   1184

In [31]:
zz_df[zz_df['2014-01'].isna()]['State'].value_counts()

 CA    56
 TX    38
 CO    19
 DC    19
 IL    13
 NY    12
 FL    12
 PA    12
 MD    11
 WA     9
 SC     9
 TN     9
 OH     8
 VA     8
 NC     8
 MI     7
 GA     7
 CT     6
 MO     5
 MA     5
 AZ     5
 OR     4
 MN     3
 IN     3
 OK     2
 LA     2
 NE     2
 UT     1
 WI     1
 AL     1
 HI     1
Name: State, dtype: int64